#!/usr/bin/ruby -W0
require 'fileutils'
require 'json'
require 'yaml'
require 'xcodeproj'
require_relative './lib/switch'
require_relative './lib/confuse'
require_relative './lib/image'
require_relative './lib/pod'
require 'optparse/subcommand' # Also requires 'optparse'
# require 'pry'

VERSION = "0.2.0"

# author: Rake Yang
# iOS工具包
# 2019-09-19

options = {}
optparse = OptionParser.new do|opt|
  opt.banner = 'Usage: toolbox command [options]'

  opt.subcommand 'pod' do |opts|
    options[:repo] = true
    opts.on('-r NAME', '--repo NAME', '设置spec仓库名称') do |name, p|
      options[:name] = name
    end

    options[:pod] = false
    opts.on('-p', '--publish', 'Pod仓库发布新版本') do |p|
      options[:pod] = p
    end
  end

  opt.subcommand 'confuse' do |opts|
    options[:confuse] = true    
    opts.on('-s', '--switch', '切换马甲包') do |p|
      options[:switch] = p
    end

    opts.on('-r', '--rename', '混淆、重命名类名和文件名') do |p|
      options[:rename] = p
    end

    opts.on('-b', '--rebuild', '重建图片哈希') do|p|
      options[:image] = true
      options[:build] = p
    end
    
    opts.on('-a', '--arrange', '整理去重') do |p|
      options[:image] = true
      options[:arrange] = p
    end
  end

  opt.on('-h', '--help', '显示帮助') do
    puts opt
    exit
  end
end

args = ARGV.dup
optparse.parse!
if args.length <= 1
  puts optparse
  exit
end

if options[:pod]
  PBPodUtility::new(options)
end

if options[:confuse]
  if options[:switch]
    PBSwitch::new(options)
  elsif options[:image]
    PBImage::new(options)
  elsif options[:confuse]
    PBConfuse::new(options)
  end
end