#!/usr/bin/ruby -w
require 'fileutils'
require 'json'
require 'yaml'
require 'xcodeproj'
require_relative './lib/param'
require_relative './lib/switch'
require_relative './lib/confuse'

# author: Rake Yang
# iOS工具箱
# 2019-09-19
class PBToolbox
  def initialize(args)
    puts "ruby version: "+RUBY_VERSION
    param = PBParam::new(args)
    if param.actionType.eql?(ACTION_TYPE_SWITCH)
      PBSwitch::new(param)
    else
      PBConfuse::new(param)
    end
  end

end

PBToolbox::new(ARGV)
